export default [
      [ {
        singer: '许嵩',
        name: '有何不可',
        album: '自定义',
        pic: 'http://p2.music.126.net/Md3RLH0fe2a_3dMDnfqoQg==/18590542604286213.jpg',
        link: '1.mp3',
      },
        {
          singer: '小辣鸡',
          name: '李帅',
          album: '什么好',
          pic: '',
          link: '1.mp3',
        },
        {
          singer: '周杰伦',
          name: '退后',
          album: '什么好',
          pic: '',
          link: 'http://pan.cccyun.cc/view.php/c94b2dcb83cece392dbd0f5366e8ec9c.mp3',
        },
        {
          singer: '新宝岛',
          name: '李帅',
          album: '什么好',
          pic: '',
          link: 'http://pan.cccyun.cc/view.php/3af6a760a936a81f378e3b7eff574dd0.mp3',
        },
        {
          singer: '薛之谦',
          name: '演员',
          album: '什么好',
          pic: '',
          link: 'http://pan.cccyun.cc/view.php/c94b2dcb83cece392dbd0f5366e8ec9c.mp3',
        },
        {
          singer: '新宝岛',
          name: '李帅',
          album: '什么好',
          pic: '',
          link: 'http://pan.cccyun.cc/view.php/3af6a760a936a81f378e3b7eff574dd0.mp3',
        },
        {
          singer: '周杰伦',
          name: '演员',
          album: '什么好',
          pic: '',
          link: 'http://pan.cccyun.cc/view.php/c94b2dcb83cece392dbd0f5366e8ec9c.mp3',
        },
        {
          singer: '小辣鸡',
          name: '李帅',
          album: '什么好',
          pic: '',
          link: 'http://pan.cccyun.cc/view.php/3af6a760a936a81f378e3b7eff574dd0.mp3',
        },
        {
          singer: '周杰伦',
          name: '退后',
          album: '什么好',
          pic: '',
          link: 'http://pan.cccyun.cc/view.php/c94b2dcb83cece392dbd0f5366e8ec9c.mp3',
        },
        {
          singer: '新宝岛',
          name: '李帅',
          album: '什么好',
          pic: '',
          link: 'http://pan.cccyun.cc/view.php/3af6a760a936a81f378e3b7eff574dd0.mp3',
        },
      ],
      [ {
        singer: '周杰伦',
        name: '演员',
        album: '什么好',
        pic: '',
        link: 'http://pan.cccyun.cc/view.php/c94b2dcb83cece392dbd0f5366e8ec9c.mp3',
      },
        {
          singer: '新宝岛',
          name: '李帅',
          album: '什么好',
          pic: '',
          link: 'http://pan.cccyun.cc/view.php/3af6a760a936a81f378e3b7eff574dd0.mp3',
        },
        {
          singer: '周杰伦',
          name: '退后',
          album: '什么好',
          pic: '',
          link: 'http://pan.cccyun.cc/view.php/c94b2dcb83cece392dbd0f5366e8ec9c.mp3',
        },
        {
          singer: '小辣鸡',
          name: '李帅',
          album: '什么好',
          pic: '',
          link: 'http://pan.cccyun.cc/view.php/3af6a760a936a81f378e3b7eff574dd0.mp3',
        },
        {
          singer: '薛之谦',
          name: '退后',
          album: '什么好',
          pic: '',
          link: 'http://pan.cccyun.cc/view.php/c94b2dcb83cece392dbd0f5366e8ec9c.mp3',
        },
        {
          singer: '新宝岛',
          name: '李帅',
          album: '什么好',
          pic: '',
          link: 'http://pan.cccyun.cc/view.php/3af6a760a936a81f378e3b7eff574dd0.mp3',
        },
        {
          singer: '周杰伦',
          name: '演员',
          album: '什么好',
          pic: '',
          link: 'http://pan.cccyun.cc/view.php/c94b2dcb83cece392dbd0f5366e8ec9c.mp3',
        },
        {
          singer: '新宝岛',
          name: '李帅',
          album: '什么好',
          pic: '',
          link: 'http://pan.cccyun.cc/view.php/3af6a760a936a81f378e3b7eff574dd0.mp3',
        },
        {
          singer: '周杰伦',
          name: '退后',
          album: '什么好',
          pic: '',
          link: 'http://pan.cccyun.cc/view.php/c94b2dcb83cece392dbd0f5366e8ec9c.mp3',
        },
        {
          singer: '小辣鸡',
          name: '李帅',
          album: '什么好',
          pic: '',
          link: 'http://pan.cccyun.cc/view.php/3af6a760a936a81f378e3b7eff574dd0.mp3',
        },
      ],
      [ {
        singer: '薛之谦',
        name: '退后',
        album: '什么好',
        pic: '',
        link: 'http://pan.cccyun.cc/view.php/c94b2dcb83cece392dbd0f5366e8ec9c.mp3',
      },
        {
          singer: '新宝岛',
          name: '李帅',
          album: '什么好',
          pic: '',
          link: 'http://pan.cccyun.cc/view.php/3af6a760a936a81f378e3b7eff574dd0.mp3',
        },
        {
          singer: '周杰伦',
          name: '演员',
          album: '什么好',
          pic: '',
          link: 'http://pan.cccyun.cc/view.php/c94b2dcb83cece392dbd0f5366e8ec9c.mp3',
        },
        {
          singer: '小辣鸡',
          name: '李帅',
          album: '什么好',
          pic: '',
          link: 'http://pan.cccyun.cc/view.php/3af6a760a936a81f378e3b7eff574dd0.mp3',
        },
        {
          singer: '周杰伦',
          name: '退后',
          album: '什么好',
          pic: '',
          link: 'http://pan.cccyun.cc/view.php/c94b2dcb83cece392dbd0f5366e8ec9c.mp3',
        },
        {
          singer: '新宝岛',
          name: '李帅',
          album: '什么好',
          pic: '',
          link: 'http://pan.cccyun.cc/view.php/3af6a760a936a81f378e3b7eff574dd0.mp3',
        },
        {
          singer: '薛之谦',
          name: '退后',
          album: '什么好',
          pic: '',
          link: 'http://pan.cccyun.cc/view.php/c94b2dcb83cece392dbd0f5366e8ec9c.mp3',
        },
        {
          singer: '新宝岛',
          name: '李帅',
          album: '什么好',
          pic: '',
          link: 'http://pan.cccyun.cc/view.php/3af6a760a936a81f378e3b7eff574dd0.mp3',
        },
        {
          singer: '周杰伦',
          name: '演员',
          album: '什么好',
          pic: '',
          link: 'http://pan.cccyun.cc/view.php/c94b2dcb83cece392dbd0f5366e8ec9c.mp3',
        },
        {
          singer: '新宝岛',
          name: '李帅',
          album: '什么好',
          pic: '',
          link: 'http://pan.cccyun.cc/view.php/3af6a760a936a81f378e3b7eff574dd0.mp3',
        },
      ]
]